url: https://alexgt1.github.io/tennis-otago/

collections:
  about:
    output: true
  facilities:
    output: true
  competitions:
    output: true
  posts:
    output: true
  clubs:
    output: true

  source: src

  paginate: 5
  paginate_path: "/news/page:num/"